create table public.user_responses (
  id bigint generated by default as identity primary key,
  interests jsonb not null default '[]'::jsonb,
  voucher_preference text null,
  full_name text null,
  email text null,
  phone text null,
  agreed boolean not null default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
-- Set up Row Level Security (RLS)
-- Enable RLS
alter table public.user_responses enable row level security;
-- Create a policy to allow anyone (anon) to insert data
create policy "Allow public inserts"
on public.user_responses
for insert
to anon
with check (true);
-- IF YOU ALREADY CREATED THE TABLE, RUN THIS INSTEAD:
-- alter table public.user_responses add column full_name text;
-- alter table public.user_responses add column email text;
-- alter table public.user_responses add column phone text;